### ISSUE TITLE
 how can I change color of carbanKit tapSwipeNavigationBar  which is same as  default UINavigationBar color of ViewControllor ?? 

### ISSUE THREAD

**Issue by subhash08** [ermalkaleci/CarbonKit#33] opened 2015-08-17 08:28 UTC
hello sir, 
with respect.
i want the color of tapSwipeNavigationBar is different from my ViewControllers default UINavigationbar`s color 
like in this pic 
![ios simulator screen shot 17-aug-2015 1 56 28 pm](https://cloud.githubusercontent.com/assets/11552671/9303518/2b3bcbaa-44fc-11e5-8136-61ab8fcbd95f.png)

**Comment by ermalkaleci** [comment] 2015-08-17 09:56
Hey @subhash08 
you mean tabs and navigationBar with the same color?

**Comment by subhash08** [comment] 2015-08-17 10:50
Hello @ermalkaleci 
sorry , week in english. 
i wants tabs and navigationBar with diffrent color 
tabs in white color and navigationBar in green color.
look  this image
"how can i change tabs background in white"
![ios simulator screen shot 17-aug-2015 4 16 37 pm](https://cloud.githubusercontent.com/assets/11552671/9303411/7b04ee88-44fb-11e5-9b75-8530dd175d1f.png)

**Comment by ermalkaleci** [comment] 2015-08-17 10:55
just set tintColor: white
```objective-c
[[CarbonTabSwipeNavigation alloc] createWithRootViewController:self tabNames:names tintColor:[UIColor whiteColor] delegate:self];
```

**Comment by subhash08** [comment] 2015-08-17 10:59
where to set ? sir @ermalkaleci

**Comment by ermalkaleci** [comment] 2015-08-17 11:07
you have the code above
please stop calling me sir, my username is OK

**Comment by subhash08** [comment] 2015-08-17 11:08
thanks @ermalkaleci

**Comment by ermalkaleci** [comment] 2015-08-17 11:09
did you fix it?

**Comment by subhash08** [comment] 2015-08-17 11:11
yes i did @ermalkaleci 
I`m calling sir just becouse of you are very senior in iOS development and I`m just a new comer.
If you don`t like I`ll not call you sir again. :)

**Comment by ermalkaleci** [comment] 2015-08-17 11:14
I'm not your boss ;-)
I am closing this issue, OK?

**Comment by subhash08** [comment] 2015-08-17 11:15
ok

**Closed** 2015-08-17 11:16 UTC

**Comment by JannyKul** [comment] 2015-10-04 11:12
I'm actually having the exact same issue. When setting the tint colour within the creation method (using the below code) the navigationbar of that view takes the same colour 

`var color: UIColor = UIColor(red: 0.7, green: 0.7, blue: 0.7, alpha: 1)
tabSwipe.createWithRootViewController(self, tabNames: names, tintColor: color, delegate: self) `

![screen shot 2015-10-04 at 12 06 02](https://cloud.githubusercontent.com/assets/14953265/10267548/6b62410a-6a90-11e5-9ad1-6ee320a18b18.png)

I have tried programmatically overriding the navigation bar color within viewdidload however this doesn't seem to work either

`UINavigationBar.appearance().backgroundColor = UIColor.greenColor()`

how did you manage to fix this issue?

Thanks very much in anticipation of your response.

**Comment by ermalkaleci** [comment] 2015-10-04 12:35
Don't copy/paste the example.
OnViewDidApper you have called setTranslucent to NO. This fit the navigation color with the same color.

**Comment by JannyKul** [comment] 2015-10-04 12:56
ah of course! you're 100% right, thank you so much for the help once again

**Comment by Narendratha** [comment] 2015-12-24 08:49
how to set the image color in navigation

**Comment by ermalkaleci** [comment] 2015-12-24 09:44
@Narendratha follow the example

**Comment by JaydeepPatel** [comment] 2016-01-23 11:44
@ermalkaleci  [[CarbonTabSwipeNavigation alloc] createWithRootViewController:self tabNames:names tintColor:[UIColor whiteColor] delegate:self];
this line where i put ? in which class ?

**Comment by ermalkaleci** [comment] 2016-01-23 18:27
Please checkout  the example project.

**Comment by JaydeepPatel** [comment] 2016-01-26 10:44
checkout .. but i can't Change NavigationBar Color. So, Please tell me the Proper Code and Guide me.

**Comment by MemetiDrak** [comment] 2016-02-02 08:24
@JannyKul how to let the line between navigationbar and carbonTabSwipeNavigation disappear?

**Comment by MemetiDrak** [comment] 2016-02-02 08:27
![simulator screen shot feb 2 2016 4 27 06 pm](https://cloud.githubusercontent.com/assets/9655508/12743611/d7d87262-c9c9-11e5-891a-3e4805944cd7.png)

**Comment by MemetiDrak** [comment] 2016-02-02 08:27
@JannyKul that grean line

**Comment by MemetiDrak** [comment] 2016-02-02 08:28
@ermalkaleci

**Comment by ermalkaleci** [comment] 2016-02-02 12:00
@MemetiDrak like you do normally. It's navigation bar shadow line

**Comment by MemetiDrak** [comment] 2016-02-02 12:12
@ermalkaleci 
Thank you for your guidance,The problem is solved now.thank you.
![simulator screen shot feb 2 2016 8 09 14 pm](https://cloud.githubusercontent.com/assets/9655508/12749064/405e6638-c9e9-11e5-8820-8d17ceb6261f.png)

**Comment by Tahir91** [comment] 2016-08-09 12:19
how to set image with name like here is showing tabbar with title and image like as carbon kit

**Comment by ioshitendra** [comment] 2016-10-03 07:27
can i change a carbankit heigth ?

**Comment by astrolka** [comment] 2016-10-15 21:18
@ermalkaleci How can i change backGroundColor of CarbonTabSwipeNavigation? 
`[[CarbonTabSwipeNavigation alloc] createWithRootViewController:self tabNames:names tintColor:[UIColor whiteColor] delegate:self];` no such method any more
Thank you!

**Comment by ermalkaleci** [comment] 2016-10-15 21:24
@astrolka  see example app

**Comment by astrolka** [comment] 2016-10-15 21:40
@ermalkaleci oh sorry, i have just understood that there is just segmentedcontrol :D 
P.s. In [this](https://github.com/ermalkaleci/CarbonKit/blob/master/Examples/CarbonKitExamples/HomeViewController.m) example i have found nothing about this issue

**Comment by ioshitendra** [comment] 2016-10-17 06:23
Hello

@ermalkaleci <https://github.com/ermalkaleci> How can text+image of
CarbonTabSwipeNavigation?
i am use  image but ui not show proper if any way to use both of them.
Thankig You

-- 
Regards
Hitendra Lariya
IOS Developer.

**Comment by ioshitendra** [comment] 2016-10-18 14:11
@ermalkaleci 
Hello 
i have two question about carbankit segment controll 
1. the first thing is how i show badge bar on carban kit segment 
2. and second thing is how to switch next controller or back  controller programatically 
please reply me .

**Comment by kristoff2016** [comment] 2017-02-04 14:35
Very good job! Thank you very much it is the best lib.

**Comment by hariios1234** [comment] 2017-03-20 04:16
how to swipe the view controllers through programmatically in carbon tab swipe navigation....

**Comment by Dhawan7** [comment] 2017-07-18 06:24
Hi 
How can I change the swipe direction of carbon kit pagecontroller.

**Comment by MandalAkash** [comment] 2017-08-08 05:00
how to set carbon kit navigation segment title text in two line

**Comment by MandalAkash** [comment] 2017-08-08 05:04
when i swipe controller carbon navigation title change but when i swipe carbon navigation but my controller not changed. how can i change my controller class when i swipe carbon navigation

**Comment by thechaudharysab** [comment] 2017-10-05 13:26
Can I make tabs like this in swift? With selected tab background color is changed and unselected tabs color is changed. If yes then how? Because all I found were setIndicatorColor, setNormalColor and setSelectedColor
<img width="877" alt="screen shot 2017-10-05 at 6 25 05 pm" src="https://user-images.githubusercontent.com/6399152/31229550-89b5151e-a9fa-11e7-9559-d8bb9810bb1f.png">

**Comment by CavalcanteLeo** [comment] 2017-10-08 03:03
since nobody gave u the code, here it is:

```
    self.carbonTabSwipeNavigation.toolbar.barTintColor = [UIColor greenColor];
    self.carbonTabSwipeNavigation.toolbar.translucent = NO;
```

**Comment by thechaudharysab** [comment] 2017-10-09 05:26
@CavalcanteLeo Thank you for your answer and this successfully changed the background color but can I change the color of selected tab? Like in the image I've attached the selected tabs is white in color and the unselected are light blue?

**Comment by chiragpurohit71085** [comment] 2018-03-12 19:12
Hi @thechaudharysab 

did you resolve this? I need to do same thing as you have asked.

**Comment by chiragpurohit71085** [comment] 2018-03-12 20:14
Hi

If anybody is looking for as asked by @thechaudharysab , here is the solution (with text only)

CarbonTabSwipeSegmentedControl.m

Create custom function

`- (void)syncSegmentBgColor {
    for (UIView *segment in self.segments) {

        if ([self.segments indexOfObject:segment] == self.selectedSegmentIndex) {
           
             segment.backgroundColor = [UIColor colorWithRed:102.0/255.0f green:124.0/255.0f blue:189.0/255.0f alpha:1];
           
        } else {
            
             segment.backgroundColor = [UIColor whiteColor];
          
        }
        
        
    }
}`

Call it from setSelectedSegmentIndex e.g

`- (void)setSelectedSegmentIndex:(NSInteger)selectedSegmentIndex {
    [super setSelectedSegmentIndex:selectedSegmentIndex];
    [self syncSegmentBgColor];
}
`

**Comment by ManojSMac** [comment] 2018-12-11 08:43
![screen shot 2018-12-11 at 2 11 51 pm](https://user-images.githubusercontent.com/26253291/49788213-c2aa0980-fd4e-11e8-9bc8-f9c48a6d3d10.png)



Is it possible to show both icon and name as Items heading

**Comment by ManojSMac** [comment] 2018-12-11 08:44
If possible kindly share the code

**Comment by saritbahuguna1** [comment] 2019-07-19 13:41
Dear @ermalkaleci ,

Hope you are doing well.

I am getting an issue only in iPad,I have CarbonTabSwipeNavigation with two tabs. in iPhone it is working fine . but in case of iPad I have issue regarding navigation i.e in status bar and CarbonTabSwipeNavigation have some black screen.
I do'nt know how it will fix. Can you help me for the same , if have any idea.
![Simulator Screen Shot - iPad Air 2 - 2019-07-19 at 19 10 25](https://user-images.githubusercontent.com/53087882/61539324-e8239200-aa58-11e9-86af-615d0193abb6.png)

Waiting for your positive feedback.

**Comment by milan-mgu** [comment] 2020-07-29 14:41
> Can I make tabs like this in swift? With selected tab background color is changed and unselected tabs color is changed. If yes then how? Because all I found were setIndicatorColor, setNormalColor and setSelectedColor
> <img alt="screen shot 2017-10-05 at 6 25 05 pm" width="877" src="https://user-images.githubusercontent.com/6399152/31229550-89b5151e-a9fa-11e7-9559-d8bb9810bb1f.png">

Did you get solution for this? I want to do same thing. but didn't found anything till now

**Comment by milan-mgu** [comment] 2020-07-29 14:42
> Can I make tabs like this in swift? With selected tab background color is changed and unselected tabs color is changed. If yes then how? Because all I found were setIndicatorColor, setNormalColor and setSelectedColor
> <img alt="screen shot 2017-10-05 at 6 25 05 pm" width="877" src="https://user-images.githubusercontent.com/6399152/31229550-89b5151e-a9fa-11e7-9559-d8bb9810bb1f.png">

Did you get solution for this ? I want to do same thing.
